### ISSUE TITLE
We would like to re-purpose this site

### ISSUE THREAD

**Issue by thriuin** [open-data/open-data.github.io-prev#3]
Hi Richard @scilib , you used this repo a few years ago for a GTEC event. We'd like to reuse and update this now for  our own work. Can you let me know if you need to retain the site. We would will rename it otherwise next week. 

Thanks,
Ross Thompson, STATCAN

**Comment by thriuin** [comment]
Since this site appears to out of use, we are archiving it for now and will be creating a new open-data.github.io. We will retain this site for the time being

**Comment by scilib** [comment]
No problem.
